// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ApertureLabs.GeneratePageObjectsExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGeneratePageObjectsPackageString = "624bd8e2-29c6-4e86-a4c3-16f0af710f04";
        public const string guidGeneratePageObjectsCmdSetString = "28086d5f-a1ae-49c8-b3b9-e854c4ee13fa";
        public static Guid guidGeneratePageObjectsPackage = new Guid(guidGeneratePageObjectsPackageString);
        public static Guid guidGeneratePageObjectsCmdSet = new Guid(guidGeneratePageObjectsCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GenerateSyncPageObjectsGroup = 0x1020;
        public const int cmdidGeneratePageObjectsCommand = 0x0100;
    }
}
