// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Method does rethrow exception.", Scope = "member", Target = "~M:ApertureLabs.Tools.CodeGeneration.Core.Options.TestOptions.ExecuteAsync(System.IProgress{System.Double},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0019:Use pattern matching", Justification = "Pattern matching has worse readability here.", Scope = "member", Target = "~M:ApertureLabs.Tools.CodeGeneration.Core.Options.TestOptions.ExecuteAsync(System.IProgress{System.Double},System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Exception is being logged instead.", Scope = "member", Target = "~M:ApertureLabs.Tools.CodeGeneration.Core.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Would cause a nested ternary statement.", Scope = "member", Target = "~M:ApertureLabs.Tools.CodeGeneration.Core.CodeGeneration.RazorPageInfoFactory.Walker.DoesPropertyExist(System.String,System.String,System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Ternary would cover too many lines. Hurts readability.", Scope = "member", Target = "~M:ApertureLabs.Tools.CodeGeneration.Core.CodeGeneration.RazorPageInfoFactory.CreateClassDeclaration(ApertureLabs.Tools.CodeGeneration.Core.CodeGeneration.RazorPageInfo,ApertureLabs.Tools.CodeGeneration.Core.CodeGeneration.RazorPageInfoFactory.UniqueNameVerifier)~Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Pattern matching with conditionals should be avoided, if else is more readable.", Scope = "member", Target = "~M:ApertureLabs.Tools.CodeGeneration.Core.CodeGeneration.RazorPageInfoFactory.GeneratedClassDocumentAsync(System.Collections.Generic.IEnumerable{System.String},ApertureLabs.Tools.CodeGeneration.Core.CodeGeneration.RazorPageInfo,Microsoft.CodeAnalysis.Document)~System.Threading.Tasks.Task{Microsoft.CodeAnalysis.Project}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ApertureLabs.Selenium.CodeGeneration.CodeGenerator.GetDocumentsWithFileExtensions(Microsoft.CodeAnalysis.Project,System.Collections.Generic.IEnumerable{System.String})~System.Collections.Generic.IEnumerable{Microsoft.CodeAnalysis.TextDocument}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ApertureLabs.Selenium.CodeGeneration.CodeGenerator.AddFileToProject(Microsoft.CodeAnalysis.Project,System.String,Microsoft.CodeAnalysis.TextDocument)~Microsoft.CodeAnalysis.Document")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ApertureLabs.Tools.CodeGeneration.Core.CodeGeneration.RazorPageInfoFactory.GenerateInterfaceDocumentAsync(System.Collections.Generic.IEnumerable{System.String},ApertureLabs.Tools.CodeGeneration.Core.CodeGeneration.RazorPageInfo,Microsoft.CodeAnalysis.Document)~System.Threading.Tasks.Task{Microsoft.CodeAnalysis.Project}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:ApertureLabs.Tools.CodeGeneration.Core.CodeGeneration.RazorPageInfoFactory.GeneratedClassDocumentAsync(System.Collections.Generic.IEnumerable{System.String},ApertureLabs.Tools.CodeGeneration.Core.CodeGeneration.RazorPageInfo,Microsoft.CodeAnalysis.Document)~System.Threading.Tasks.Task{Microsoft.CodeAnalysis.Project}")]

