//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApertureLabs.Selenium.Analyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApertureLabs.Selenium.Analyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes should implement IPageObject OR IPageComponent, not both..
        /// </summary>
        internal static string AnalyzerDescriptionImpl {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes implementing IPageObject or IPageComponent should be suffixed with &apos;Page&apos; and &apos;Component&apos; respectively..
        /// </summary>
        internal static string AnalyzerDescriptionSuffix {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public members of IPageObjects and IPageComponents should be virtual..
        /// </summary>
        internal static string AnalyzerDescriptionVirtual {
            get {
                return ResourceManager.GetString("AnalyzerDescriptionVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes should implement IPageObject OR IPageComponent, not both..
        /// </summary>
        internal static string AnalyzerMessageFormatImpl {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes implementing IPageObject or IPageComponent should be suffixed with &apos;Page&apos; and &apos;Component&apos; respectively..
        /// </summary>
        internal static string AnalyzerMessageFormatSuffix {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public members of IPageObjects and IPageComponents should be virtual..
        /// </summary>
        internal static string AnalyzerMessageFormatVirtual {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormatVirtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes should implement IPageObject OR IPageComponent, not both..
        /// </summary>
        internal static string AnalyzerTitleImpl {
            get {
                return ResourceManager.GetString("AnalyzerTitleImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class name isn&apos;t suffixed with &apos;Page&apos; or &apos;Component&apos;..
        /// </summary>
        internal static string AnalyzerTitleSuffix {
            get {
                return ResourceManager.GetString("AnalyzerTitleSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public member isn&apos;t virtual.
        /// </summary>
        internal static string AnalyzerTitleVirtual {
            get {
                return ResourceManager.GetString("AnalyzerTitleVirtual", resourceCulture);
            }
        }
    }
}
