// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Conditional would be less readable here.", Scope = "member", Target = "~M:ApertureLabs.Selenium.Components.TinyMCE.TinyMCEComponent.Load~OpenQA.Selenium.Support.UI.ILoadableComponent")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Conditional would be less readable here.", Scope = "member", Target = "~M:ApertureLabs.Selenium.Css.CssColor.ColorFromHsl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Conditional would be less readable here.", Scope = "member", Target = "~M:ApertureLabs.Selenium.Components.TinyMCE.MenuComponent.GetItemByText(System.String,System.StringComparison)~ApertureLabs.Selenium.Components.TinyMCE.MenuItem")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Conditional would be less readable here.", Scope = "member", Target = "~M:ApertureLabs.Selenium.Components.TinyMCE.MenuComponent.GetItemByClass(System.String,System.StringComparison)~ApertureLabs.Selenium.Components.TinyMCE.MenuItem")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Conditional would be less readable here.", Scope = "member", Target = "~M:ApertureLabs.Selenium.Css.CssColor.ColorFromHsl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0045:Convert to conditional expression", Justification = "Conditional would be less readable here.", Scope = "member", Target = "~M:ApertureLabs.Selenium.TextHelper.ExtractInteger(System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:ApertureLabs.Selenium.SeleniumServerStandaloneWrapper`1.ExtractPort(System.String)~System.Nullable{System.Int32}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1716:Identifiers should not match keywords", Justification = "Naming conflict between the element name and conventions. Violating the naming convention is preferred over breaking the pattern.", Scope = "namespace", Target = "~N:ApertureLabs.Selenium.WebElements.Option")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "Naming conflict between the js and dotnet types.", Scope = "type", Target = "~T:ApertureLabs.Selenium.Js.JavaScriptType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Should be ok.", Scope = "member", Target = "~P:ApertureLabs.Selenium.Js.JavaScript.Arguments")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:ApertureLabs.Selenium.Components.TinyMCE.MenuComponent.GetItemByClass(System.String,System.StringComparison)~ApertureLabs.Selenium.Components.TinyMCE.MenuItemComponent")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:ApertureLabs.Selenium.Components.TinyMCE.MenuComponent.GetItemByText(System.String,System.StringComparison)~ApertureLabs.Selenium.Components.TinyMCE.MenuItemComponent")]

